### PR TITLE
Replace deprecatet HttpEntity.consume with EntityUtils.consume

### PR DESCRIPTION
**Pull request by oxygen0211**
fixes issue #633

### CODE REVIEW

**Comment by oxygen0211** [comment]
Apparently, in certain cases (at least in the integration tests), EntityUtils is not available. Have to check this.

**Comment by johanhaleby** [comment]
Thanks for the pull request. In what scenarios are `EntityUtils` not available? Do you mean in some version of Apache HTTP Client?

**Comment by oxygen0211** [comment]
Turned out it was an error on my side, I missed out an import that wasn't added automatically by Eclipse (I'm not doing much groovy and thus my env isn't really prepared for it). With ec728f6, those concerns are gone

**Comment by johanhaleby** [comment]
Oh OK! Great I'll bring it on.

**Pull request merged**
